---
k3s_version: v1.24.4+k3s1
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable traefik --node-external-ip {{ master_ip }} --flannel-backend wireguard-native "
extra_agent_args: "--node-external-ip {{ master_ip }}"

ansible_become_method: su
wireguard_mask_bits: 8
wireguard_port: 51871

host_key_checking: false